### ISSUE TITLE
Please add documentation on fzf-grep/file modules

### ISSUE THREAD

**Issue by TimisRobert** [andreyorst/fzf.kak#106]
Spent a lot of time figuring it out since I just started using Kakoune and it's plugins.
Please mention somewhere that if you need to configure alternative grep and file you should do this:

plug "andreyorst/fzf.kak" config %{
  map global normal <c-p> ': fzf-mode<ret>'
} defer "fzf-file" %{
  set-option global fzf_file_command 'fd'
} defer "fzf-grep" %{
  set-option global fzf_grep_command 'rg'
}

Thanks

**Comment by andreyorst** [comment]
Pull request is welcome :slightly_smiling_face:

**Comment by TimisRobert** [comment]
#107
