### ISSUE TITLE
fzf window closes immediatly on x11

### ISSUE THREAD

**Issue by TeddyDD** [andreyorst/fzf.kak#15]
## Problem description
Running ~~any~~ file related command from fzf mode results in new terminal window blinking for a split of a second. It closes immediately after that. Info box stays open. I did bisect on changes since v0.1.2 and first bad commit is 8ae03b154e3043d8b542672201ba482091b6d61d

Buffer selector, change directory and buffer search works fine.

## Steps to reproduce
1. git checkout 8ae03b154e3043d8b542672201ba482091b6d61d
2. run kak outide of tmux
3. run any fzf-mode command

## Environment information
Kakoune version: v2018.09.04
OS version: Void 4.18.13_1 x86_64 GenuineIntel uptodate rFFFFFFFF
`sh` executable version: dash-0.5.10.2
fzf version: 0.17.5

Edit:

It seems that `fzf_preview` was true by default, disabling it fixes the problem. 

Okay, I don't have any compatible highlighter installed so it fails because `fzf_preview` is true by default.

**Comment by andreyorst** [comment]
Hm. That's weird, because I shouldn't fail if no highlighter is installed. Because it fallbacks to `cat`. I have no highlighter in my Termux instance, and it works fine there, though inside tmux. I'll investigate it

**Comment by andreyorst** [comment]
@TeddyDD does `fzf-buffer` work? It uses different implementation. If It isn't working too, there's nothing to do with preview. Also please check `fzf-cd`

**Comment by TeddyDD** [comment]
buffer and cd works. I checked if this might be terminal related but both kitty and xst gives me the same result

**Comment by andreyorst** [comment]
I've found the issue. Please try with latest master

**Comment by andreyorst** [comment]
No. Actually not. The problem is that the size calculation isn't happening.

**Comment by andreyorst** [comment]
I've pushed modified version, in which `$pos` variable contains default value. Please try to launch fzf with it

**Comment by andreyorst** [comment]
I've pushed `fix_preview` branch, can you please try it? It works in my setup, I even symlinked sh to dash. Though It worked for me whole time, so my configuration can't be referenced.

**Comment by TeddyDD** [comment]
It doesn't close terminal window so you probably fixed it :)

Problem is apparently fzf uses `$SHELL` in preview command so preview it's broken on Fish shell. I fixed it with this patch

```diff
diff --git i/rc/fzf.kak w/rc/fzf.kak
index a038c9..ec160c 100644
--- i/rc/fzf.kak
+++ w/rc/fzf.kak
@@ -334,7 +334,7 @@ define-command -hidden fzf -params 2..3 %{ evaluate-commands %sh{
     elif [ ! -z "${kak_opt_termcmd}" ]; then
         path=$(pwd)
         additional_flags=$(echo $additional_flags | sed "s:\$pos:\\\\\$pos:")
-        cmd="$kak_opt_termcmd \"sh -c \\\"cd $path && $preview_pos $items_command | fzf --expect ctrl-q $additional_flags > $tmp\\\"\""
+        cmd="$kak_opt_termcmd \"sh -c \\\"SHELL=/bin/sh; export SHELL; cd $path && $preview_pos $items_command | fzf --expect ctrl-q $additional_flags > $tmp\\\"\""
     else
         echo "fail termcmd option is not set"
         exit
```

**Comment by andreyorst** [comment]
`/bin/sh` is not always there. For example in Termux there's no `/bin/sh`

**Comment by andreyorst** [comment]
@TeddyDD can you please try the latest `fix_preview` branch?

**Comment by TeddyDD** [comment]
It doesn't work, terminal shows up for split of a second and closes.

**Comment by andreyorst** [comment]
fish doesn't support `$(...)`... mother of god why...

**Comment by TeddyDD** [comment]
yeah, but that shoudn't matter since Kakoune uses posix shell in expansions, right?

**Comment by andreyorst** [comment]
yeah, but I pass shell command to terminal via `$termcmd -e`, then I pass it to `sh -c` to actually do the thing. This way it should be more portable, since we always use `sh`. Now I try to debug this 3 screen line command in fish, and the syntax is wrong in the places where I least expect it to be.

**Comment by andreyorst** [comment]
@TeddyDD with latest changes, still doesn't work?

**Comment by TeddyDD** [comment]
um, you haven't pushed anything new to fix_preview

**Comment by andreyorst** [comment]
Oh. Sorry. I didn't noticed that my connection was off. I've pushed the changes

**Comment by TeddyDD** [comment]
nope, still blinking terminal,

**Comment by andreyorst** [comment]
Can I ask you to try with another login shell? Althoughit works for me in KDE and Mate, with bash, zsh, and fish as a login shells...

**Comment by TeddyDD** [comment]
sure, I'll try and report back

**Comment by andreyorst** [comment]
I've installed kitty, and now it isn't working for me either

**Comment by TeddyDD** [comment]
I tried with bash as login shell, it doesn't help. I tried it under st and kitty

**Comment by andreyorst** [comment]
I've noticed that this doesn't work with kitty, and alacritty when they set as `termcmd`. If I change it, it works. Try changing `termcmd` to some common terminal, like gnome terminal? Maybe it is the issue with kitty, as it need some additional argument. Currently, setting `termcmd` to `termite -e` `gnome-terminal -e` and `mate-terminal -e` makes it work.

**Comment by andreyorst** [comment]
I see.
when alacritty installed `termcmd` equals to `alacritty sh -c`
when kitty installed `termcmd` equals to `kitty sh -c`
I use termite, and with it `termcmd` equals to `termite -e`

Seems likse `-e` isn't compatible with `sh -c` in some ways.

**Comment by andreyorst** [comment]
Ok now I know where to dig. Expect a fix in couple of hours :)

**Comment by andreyorst** [comment]
@TeddyDD should work now. I've tested with all possible terminals

**Comment by TeddyDD** [comment]
it works, awesome job!

**Comment by andreyorst** [comment]
> awesome job

issue solved exactly in 30 comments.

I'll merge this into master now
