### ISSUE TITLE
fzf-cd does not work in mac

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/fzf.kak#17]
There is only `..` in fzf panel without directories listing.
I suspect there are some differences between mac's find and gnu find. 

Also I'd like to set custom command ([blsd](https://github.com/junegunn/blsd) for example) for `fzf-cd` to avoid such issues.

**Comment by andreyorst** [comment]
Hm. I'm not sure about mac's `find`, but I'll add ability to change the command. I'd like to ask you to debug this command in MacOS:

```sh
(echo .. && find \( -path '*/.svn*' -o -path '*/.git*' \) -prune -o -type d -print)
```

Maybe we should drop `\( -path '*/.svn*' -o -path '*/.git*' \) -prune -o` part for good.

**Comment by andreyorst** [comment]
I've committed the workaround with settable cd command, however I would like to find solution with default cd value for the script, so MacOS users could use it without configuration until it's really needed

**Comment by andreyorst** [comment]
Also please provide your environment information- your `shell`, `sh` executable version, `find` executable version. It is hard to test this without all that information, since I'm no guru.

**Comment by andreyorst** [comment]
Turns out that MacOS uses BSD `find`, instead of GNU `find`. So there are GNU `findutils` in brew, that can solve issue for you.

**Comment by vbauerster** [comment]
I use zsh 5.6.2 (x86_64-apple-darwin17.7.0), I prefer setting custom command to shadowing original find utility. Thank you for quick solution.

**Comment by andreyorst** [comment]
Ok, `find` just seems like the most widespread utility, that can be used. Closing this then.
