### ISSUE TITLE
Split fzf-tag to own file.

### ISSUE THREAD

**Issue by Delapouite** [andreyorst/fzf.kak#22]
When finally digging in the source I was astonished at first sight that `fzf.kak` was 1640 lines!
I thought "what? how could this plugin be so big?".

It turns out that about 1200 of this lines are dedicated to support ctags functionalities. For many esoteric languages rarely seen in the modern wild. I understand your desire to offer a complete experience but I also feel that it's way too much and a bit out of the core scope of this plugin.

Moreover ctags possibilities are quite redundant (and somehow not as powerful) to the ones found in LSP.
So I would suggest to split the fzf-tag part in a companion file.

This way with `plug.kak` with the `noload` switch, everyone is in control and can source the part they need:

```
plug "andreyorst/fzf.kak" "noload" %{
    source "%val{config}/plugins/fzf.kak/rc/fzf.kak"
    source "%val{config}/plugins/fzf.kak/rc/fzf-tag.kak" # optional
}
```

**Comment by andreyorst** [comment]
I've thought about it, but I don't like this (actually you don't need quotes around) `noload` trick. A proper mechanism of loading parts is needed and should be handled by the plugin, not plugin manager, which I gonna implement once I finish some more things in **plug.kak**. So I will rewrite the script in this month, so I'd like not to change anything right now. I want to do some simplifications, externalizations, and avoid escaping hell. I just can't bounce between two plugins, so I do portional updates there and here.

I've also thought about adding support of LSP, I'm planning to talk with @ul about it.

**Comment by andreyorst** [comment]
@Delapouite I've started to work on [v1.0.0 branch](https://github.com/andreyorst/fzf.kak/tree/v1.0.0), that will be sort of re-write of a plugin, and I've already moved all fzf commands to separate files. Can you check if this is good for your taste?

**Comment by andreyorst** [comment]
Done
