### ISSUE TITLE
File listing fails, yet VCS/Buffer/etc listing works

### ISSUE THREAD

**Issue by leeola** [andreyorst/fzf.kak#23]
## Steps to reproduce

1. run :fzf-mode
2. type f to choose files.

## What should happen

As in the screenshots, the popup of fzf inside of Kakoune should list files, and filter them as you type.

## What happens instead

The fzf section of Kakoune is blank. No files are listed. Likewise typing in the window does not show any additional results.

Strangely, using `v` for the VCS files works great, and as expected.

Is this user error? Running fzf by itself from the CLI works as expected.. so I'm not sure what I'd be doing wrong. And largely, fzf.kak seems to be working in other modes. Buffer, Search, Edit VCS Repo all seem to work fine. The plain file listing does not.

## Environment information
Kakoune version: Kakoune v2018.09.04-33-gba9d97ff
OS version: MacOS 10.14
`sh` executable version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
fzf version:  0.17.5 (brew)

`find` version:
`ag` version:
`fg` version:
`git` version:
`ctags` version:

**Comment by andreyorst** [comment]
Does `*debug*` buffer shows any errors? My guess gonna be that you're using BSD Find, and since my system isn't really Unix (MacOS and BSD are Unix), but GNU/Linux I use GNU Find which may differ from BSD one. Try to set find command to different finder, like `fd` or `ripgrep`. Or try to use more basic find command. You can customize find command with `fzf_fle_command` option

**Comment by leeola** [comment]
Yup, it's a BSD OSX find, not sure where the version is, but yea. My `*debug*` did not report anything *I think*. There is this:

```
shell stderr: <<<
expr: not a decimal number: '1542138271N'
expr: not a decimal number: '1542138271N'
>>>
Error: 'start: ' time is bigger than 'end: ' time
```

In the debug, but that I believe is a `plug.kak` error I've not yet figured out, nothing to do with fzf I think.

I switched the command to ripgrep and find now works, appreciated. Perhaps in the future an error could be reported if `find` is not GNU?

Regardless, I'll close this as I think it's working as designed. :+1:

**Comment by andreyorst** [comment]
> In the debug, but that I believe is a `plug.kak`

Yes. It's a profiler, that measures startup time in nanoseconds. Seems like BSD date is different from GNU date too. 

> I switched the command to ripgrep and find now works, appreciated. Perhaps in the future an error could be reported if `find` is not GNU?

I'm not sure if it is possible. However fzf. kak should work with BSD find OOTB. I'll troubleshoot this on OpenBSD. You can disable profiler by setting `plug_profiler` option to `false`
