### ISSUE TITLE
Buffers are shown in one line

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/fzf.kak#27]
## Problem description

All buffers are shown in one line:
[![Screenshot-2018-11-27-at-00-33-29.png](https://i.postimg.cc/XqQFXW4q/Screenshot-2018-11-27-at-00-33-29.png)](https://postimg.cc/WqqtfQDc)

Possible solution hint:
[fzf wiki page](https://github.com/mawww/kakoune/wiki/Fuzzy-finder) says:
```
# the original version no longer works since kak_buflist is no longer ":" separated.
# this one works even you have single quote or newline in file names.

define-command -docstring 'Invoke fzf to select a buffer' fzf-buffer %{
    evaluate-commands %sh{
        BUFFER=$(
            (
                eval "set -- $kak_buflist"
                while [ $# -gt 0 ]; do
                    printf "%s\0" "$1"
                    shift
                done
            ) |
            fzf-tmux -d 15 --read0
        )
        BUFFER=${BUFFER/\'/\'\'}
        if [ -n "$BUFFER" ]; then
            printf "buffer '%s'" "${BUFFER}"
        fi
    }
}
```

## Environment information
Kakoune version: kakoune git ` 6c54c474`
OS version: MacOS 10.14.1
`sh` executable version: `zsh 5.6.2 (x86_64-apple-darwin18.0.0)`
fzf version: `0.17.5 (b46227d)`

**Comment by andreyorst** [comment]
> sh executable version: zsh 5.6.2 (x86_64-apple-darwin18.0.0)

Do I understand correctly that you have sh symlinked to zsh?

what does this command produce?
```sh
printf "'hello' 'world'" | sed "s/^'//;s/'$/\n/;s/' '/\n/g"
```

also please post the result of this expansion
```kak
:echo -debug %sh{printf "%s\n" "$kak_buflist"}
```

**Comment by andreyorst** [comment]
Should be fixed now.

**Comment by andreyorst** [comment]
Thankfully to this issue, I've also tested that previous implementation wasn't able to open buffers like `file'name` and `file"name`

However I'm still curious why it wasn't working on MacOS
