### ISSUE TITLE
Change directory with tree preview

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/fzf.kak#28]
Change directory command may check if `tree` command is available and if so display directory preview, similar to following example:
[![Screenshot-2018-11-27-at-00-52-47.png](https://i.postimg.cc/G2pbdn7q/Screenshot-2018-11-27-at-00-52-47.png)](https://postimg.cc/v1CJtkdV)

**Comment by andreyorst** [comment]
wouldn't it bring huge overhead on deep directories?

**Comment by vbauerster** [comment]
We can mitigate overhead by applying dir only key `tree -d` and limit preview let say to 300 lines.

**Comment by andreyorst** [comment]
Ok. I'll add this as a configurable parameter in the same way how other highlighters are done.

**Comment by andreyorst** [comment]
I've added it in [preview-directories](https://github.com/andreyorst/fzf.kak/tree/preview-directories) branch. Can you report back if it is working for you or something should be changed?

**Comment by vbauerster** [comment]
Yes it works as expected. Nice job!
