### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by JJK96** [andreyorst/fzf.kak#30]
## Problem description

If I select a file using the fzf finder it is not actually opened
Possibly I am missing some dependencies?
I installed using `plug`.
I get no errors in the debug log of kakoune.

## Steps to reproduce

1. Open fzf mode
2. Press `f` to open file
3. Select the file
4. Press <ret> to open it

## What should happen

The file should be opened in the buffer

## What happens instead

There is a message asking me to choose between opening in a new buffer or a new window, however, after choosing still nothing happens.

## Environment information
Kakoune version: r7039.d1274836-1
OS version: Arch Linux 4.19.6-arch1-1-ARCH
`sh` executable version: GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
fzf version: 0.17.5

`find` version: find (GNU findutils) 4.6.0

**Comment by andreyorst** [comment]
> Kakoune version: r7039.d1274836-1

That's not a version, you can obtain proper one by executing `kak -version`

> Possibly I am missing some dependencies?

There's no dependencies but fzf itself with exceptions for ctags and VC systems.

> If I select a file using the fzf finder it is not actually opened

Does file has any special characters in it? It may be escaping issue.

> There is a message asking me to choose between opening in a new buffer or a new window, however, after choosing still nothing happens.

That's really strange. Does any other fzf command work for you? Buffer, search? Does VCS opens any files?

> There is a message asking me to choose between opening in a new buffer or a new window

Does it happens when only fzf.kak plugin is installed, eg with no other configurations were made in your kakrc?

**Comment by JJK96** [comment]
>That's not a version, you can obtain proper one by executing kak -version
Kakoune v2018.09.04-249-gd1274836
> Does file has any special characters in it? It may be escaping issue.
I tried it with kakrc, which has no strange characters
>That's really strange. Does any other fzf command work for you? Buffer, search? Does VCS opens any files?
Changing directory and vcs file open also don't work for me.
>Does it happens when only fzf.kak plugin is installed, eg with no other configurations were made in your kakrc?
I tried with only plug fzf installed and had the same problems

**Comment by andreyorst** [comment]
> Kakoune v2018.09.04-249-gd1274836

Unfortunately my version differs from yours: v2018.10.27-85-gb897a18a, but I doubt that this is the case for the issue.

Are you using tmux? If not, what `termcmd` option is set in Kakoune? You can check it with `:echo %opt{termcmd}` inside kakoune.

> I tried with only plug fzf installed and had the same problems

And no other configurations but fzf itself were applied? I mean your own configurations which are not related to plugins. If you can reproduce this with `fzf.kak` and `plug.kak` all alone in your kakrc, that would be easier to investigate. Minimal configuration is always easier to track down, you know.

**Comment by andreyorst** [comment]
I can't repro. I'm using Archlinux too, and all other system packages seems to have same version as yours. That's weird. I've never seen this message to be honest:

> There is a message asking me to choose between opening in a new buffer or a new window

**Comment by JJK96** [comment]
>There is a message asking me to choose between opening in a new buffer or a new window

![deepinscreenshot_select-area_20181206134924](https://user-images.githubusercontent.com/11193274/49585132-d70c9180-f95d-11e8-9a2c-9dda8f203f50.png)

Furthermore, I can confirm that it does work in tmux, so the problem only occurs with x11 windows (using termite or urxvt).

**Comment by andreyorst** [comment]
Now I see. Indeed this isn't working in termite. For some reason my termcmd was `kitty` even if I launched kakoune from termite (both terminals looks identical on my configuration). I'll check it.

**Comment by andreyorst** [comment]
I see this error message:
```
(termite:25101): GLib-WARNING **: 17:04:41.504: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
```

**Comment by JJK96** [comment]
Your `termcmd` is `kitty` because of this piece of code in x11.kak

```bash
   for termcmd in 'alacritty      -e sh -c' \
                   'kitty             sh -c' \
                   'termite        -e      ' \
                   'urxvt          -e sh -c' \
                   'rxvt           -e sh -c' \
                   'xterm          -e sh -c' \
                   'roxterm        -e sh -c' \
                   'mintty         -e sh -c' \
                   'sakura         -x      ' \
                   'gnome-terminal -e      ' \
                   'xfce4-terminal -e      ' ; do
```

**Comment by andreyorst** [comment]
Should work fine now

**Comment by JJK96** [comment]
nice fix, but how is `fzcmd` now removed?

**Comment by andreyorst** [comment]
`rm fzfcmd` is inside the `fzfcmd`
