### ISSUE TITLE
Split capabilities for opening buffers (not just files)

### ISSUE THREAD

**Issue by supermarin** [andreyorst/fzf.kak#31]
## Steps to reproduce

1. Enter fzf-mode
2. Press `b`
3. Select the buffer

## What should happen

After selecting the buffer, you should be able to `<c-v> or <c-s>` to re-split the pane.
This should potentially apply to not just buffers, but anything else you might want to fuzzy open in the future.

## What happens instead

You're only able to press `<ret>` and open in the current pane / replace the current buffer.

Didn't attach a detailed sys report since I don't have anything much customized, this is a fzf.kak internal.

**Comment by andreyorst** [comment]
I don't use `fzf-buffer` much so I've forgotten that this might be handy.
