### ISSUE TITLE
Does not work with tmux

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/fzf.kak#32]
None of the shortcuts work with tmux, I mean no new pane opens.

- fzf version: 0.17.5 (b46227d)
- zsh 5.6.2 (x86_64-apple-darwin18.0.0)
- tmux: 2.8
- kak: 090ccafa8d64b24c0e6fb22a75e91c9b1f348cc2

**Comment by andreyorst** [comment]
kakoune no more has `tmux-new-"`. I'll see what can be done

**Comment by andreyorst** [comment]
I've fixed this within [terminal_wrapper](https://github.com/andreyorst/fzf.kak/tree/termina_wrapper) branch. I don't like implementation, so I'll spent some more time on it. But it works now

**Comment by andreyorst** [comment]
Fixed by #33
