### ISSUE TITLE
[Feature Request] Grep with skim

### ISSUE THREAD

**Issue by andreyorst** [andreyorst/fzf.kak#39]

**Comment by andreyorst** [comment]
@lammermann I've pushed a commit that makes it work, but expect bugs for now. I'm not sure what format for grep command should be used, as I need to parse it for filename and the search pattern or the line number. Currently the pattern everything before first `:` is filename, and everything after is the search pattern. But I suppose it's better to use a line number here, because searching needs lots of escaping, and I'm not capable of hanling all cases. What do you think?

**Comment by andreyorst** [comment]
Actually, I've played with it using line numbers, and it feels OK. Kinda matches to how `fzf-search` works.

**Comment by lammermann** [comment]
Thank you.
Today I installed it and I think I'm already addicted to it.
