### ISSUE TITLE
[Feature Request] Fuzzy search buffer

### ISSUE THREAD

**Issue by TeddyDD** [andreyorst/fzf.kak#4]
Since fzf is good at fuzzy finding it would be nice to have `search and jump to line` command that would serach current buffer using fzf. 

I toyed with this idea a little, here is a prototype. It returns line number that can be used with select command. WDYT?

`nl -b a -n ln some-file | fzf --reverse | cut -f '1'`

**Comment by andreyorst** [comment]
I was toying with quite (but not) the same Idea lately, however I think that such search should work somewhat similar to ctags-search, but instead of providing tags in several files, several locations in current file should be prompted to the user.

So I think that we should get all words in file, `uniq` them, and after user finds a word, prompt a location of this file, or execute a search. That's how it does visual studio code.

As for your idea - I like it, I'll see what we can do.

**Comment by andreyorst** [comment]
Well this works with slight modifications of main fzf command - adding third optional parameter additional arguments:

```kak
define-command fzf-buffer-search %{
	fzf "execute-keys $1 g" "nl -b a -n ln %val{buffile}" "--reverse | cut -f '1'"
}
```

I think that this could be used to achieve your goal.

**Comment by TeddyDD** [comment]
fzf shows up correctly but jump doesn't work

**Comment by andreyorst** [comment]
Hm It worked, but now not working for me either. Weird. I'll doublecheck everything

**Comment by andreyorst** [comment]
This is really weird. Removing `--expect ctrl-w` breaks everything:
```sh
cmd="$items_command | fzf-tmux -d 15 --color=16 --expect ctrl-w $additional_flags > $tmp"
```

**Comment by andreyorst** [comment]
@TeddyDD You can try again, I've tested, It works, however removing `--expect ctrl-w` from fzf command will break `fzf-search-buffer` and `fzf-cd` commands. Don't know why. I'll leave it till tomorrow in this state for now.
![image](https://user-images.githubusercontent.com/19470159/46041632-eb414080-c11b-11e8-811c-34619d8cc6dd.png)

**Comment by andreyorst** [comment]
Buffer search should be ready for use

**Comment by TeddyDD** [comment]
I tested it, still doesn't work, after selecting line info box stays open. Should I open another issue?

**Comment by andreyorst** [comment]
Just to make sure, you're using master branch?

It works for me in termux tmux, and in my kde with konsole and termite. What's your environment?

**Comment by andreyorst** [comment]
Ah I see, for some reason It doesn't work outside of tmux. I'll check it.

**Comment by TeddyDD** [comment]
Kitty/st, Fish user shell, dash as bin/sh. I should install tmux for testing :)

**Comment by andreyorst** [comment]
@TeddyDD can you please try with current master?

**Comment by andreyorst** [comment]
@TeddyDD gently ping

**Comment by TeddyDD** [comment]
It works now on master, thank you. Sorry for late reply :)

**Comment by andreyorst** [comment]
Great!
