### ISSUE TITLE
fzf-vcs issues when ran from subdir

### ISSUE THREAD

**Issue by jcpetruzza** [andreyorst/fzf.kak#42]
I sometimes run `kak` from a particular directory within a git repo (e.g. if it's a big repo, and I only care about a smaller part). If I then try to use ` fzf-vcs`, whichever file I chose, it will fail to open since it will use the relative path from the root of the repository. 

A related question is whether all files should be listed in this case or only those beneath the cwd. In my opinion, the latter would be a better (default) behavior.

**Comment by andreyorst** [comment]
Oops. I don't use these commands myself, because I work on remote server mounted with sshfs, and my machine has more ercent version of svn, which isn't compatible with the one on the remote, so these commands are may not have been tested properly.

I'll check this asap.

**Comment by andreyorst** [comment]
should work fine now, testing is welcome

**Comment by jcpetruzza** [comment]
This is now working for me, thanks a lot!
