### ISSUE TITLE
Spring refactoring

### ISSUE THREAD

**Issue by andreyorst** [andreyorst/fzf.kak#43]
Spring is all on it's way, birds sing, blossoms grow, code is being rewritten.

Some critical moments need to be visited:
- There's now a centralized way to handle terminal windows outside of tmux, with `terminal` command that should be used instead of `termcmd` option. This will fix #40. Althought this may require to fully rewrite [fzf.kak](https://github.com/andreyorst/fzf.kak/blob/master/rc/fzf.kak), I was planning to do it anyway.
- My `fzf` command is **ugly** af. Argument handling is painful and other things are way too complicated, which results in really awkward methods of writing supplement scripts. I suppose a full featured argument parsing algorithm will clean this mess up.
- Something should be done with getting of the output of  fzf

**Comment by elasticdog** [comment]
Just wanted to say thank you for your work on fzf.kak, and that I'm excited to see the refactoring work. Similar to #40, I'm using a different terminal emulator (kitty), and refactoring to use the standard `terminal` aliases without assuming tmux would make a huge difference for my workflow. I know there are others out there with the same setup that have struggled: https://github.com/mawww/kakoune/issues/2266#issuecomment-467938982

It sounds like you have a good plan for the cleanup, but please let me know if you'd like a hand or just another set of eyes on the proposed changes. Cheers!

**Comment by andreyorst** [comment]
I've tested fzf on kitty, it should work without tmux just fine. What difficulties do you have?

**Comment by elasticdog** [comment]
Just that it opens a new `os` window type rather than a normal Kitty window (which is the default behavior of `kitty @ new-window`, so it's a little slow and jarring, and then when fzf is complete, the window goes away and focus is not returned to the editor. It functionally works, but it's not as nice as the tmux split behavior, if that makes sense?

**Comment by laelath** [comment]
I can confirm that trying to open fzf under kitty results in a window that opens and immediately closes. There's no output to the debug buffer.
I've also found that if I manually set `termcmd` to a differently terminal, it also opens that one and immediately closes, so far for any terminal I test (with the initial terminal being kitty).

**Comment by andreyorst** [comment]
Strange, just installed kitty and It works.
```
$ kitty -v
kitty 0.13.3 created by Kovid Goyal
```

**Comment by laelath** [comment]
It's working fine, it's just calling x11 to open a new window. Something that kitty does is have it's own internal windows that the kakoune kitty support allows you to use.

Here's what's currently happening:
![Screenshot_20190318-112907](https://user-images.githubusercontent.com/9309437/54554269-518f7900-4971-11e9-870d-fa936037ce1a.png)

Here would be a desired outcome:
![Screenshot_20190318-112930](https://user-images.githubusercontent.com/9309437/54554478-c1056880-4971-11e9-8dc7-708c2fe20986.png)
With fzf taking the place of the right kakoune window.

Which is precisely what rewriting fzf.kak to use the builtin `terminal` alias would do.

**Comment by andreyorst** [comment]
> it's just calling x11 to open a new window.

Well it was a design choice to support terminals via X11, because there are plenty of those which allow splitting (terminator, konsole, iTerm2, tilix, etc), and I can't support them all in terms of creating splits of desired size, like I do in tmux. If something like https://github.com/mawww/kakoune/issues/1363 will be more flexible and will accept `size` and `side` via arguments, it will be more flexible in the future.
