### ISSUE TITLE
Populate *grep* buffer when selecting multiple candidates in `fzf-sk-grep`

### ISSUE THREAD

**Issue by alexherbo2** [andreyorst/fzf.kak#44]
How to grep file contents and get the file, line and column in results.  And also the preview.

**Comment by andreyorst** [comment]
Sorry, not sure what you mean by "grep file contents. There are currently two commands, one is `sk-grep` that is bound to <kbd>g</kbd> in `fzf-mode` and provides interactive grep over current directory recursive, and `fzf-search`, which is bound to <kbd>s</kbd> in `fzf-mode` and allows you to narrow through contents of current buffer but it is not `grep`, it is pure fzf filtering.

`sk-grep` is only available if [skim](https://github.com/lotabout/skim) is installed in your system.

**Comment by andreyorst** [comment]
Ah, maybe I get it.

Well, I've designed `sk-grep` to be simple and work like `fzf-searc` does. We can make it use preview feature, and display line numbers, but it will require tweaking the implementation. It's not configurable right now.

**Comment by alexherbo2** [comment]
It’s more about skim than fzf.kak, but the grep command is evaluated after each key-press?  How about the performance.

Finally, I thought it might be interesting for `sk-grep` to work with multiple selections, by populating the grep buffer, so search results are reusable with `grep-next-match` and `grep-previous-match`.

**Comment by andreyorst** [comment]
> the grep command is evaluated after each key-press? How about the performance.

There is no other way to get new results, as all currently existing tools work this way. If there ever will be incremental grep program, it would be better in terms of performance, of course.

> I thought it might be interesting for sk-grep to work with multiple selections, by populating the grep buffer, so search results are reusable with grep-next-match and grep-previous-match.

There are two points here:

1. It meant to be used as incremental search tool, for basic `grep` usage Kakoune provides useful command already.
2. I'm not sure if it will be possible to pass default text to `fzf` or `skim` without something like `tmux send-keys`, and fzf.kak supports X11 windows too, so I don't see a way to perform this.

**Comment by alexherbo2** [comment]
I was referring to the composability of both when selecting multiple elements with <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> from fzf: jump to the first match and populate the grep buffer, so that `grep-next-match` and `grep-previous-match` can cycle through the results.

It’s the same idea than doing a search with <kbd>/</kbd>, then be able to jump to the next occurrence with <kbd>n</kbd> and previous with <kbd>Alt</kbd> + <kbd>n</kbd>.

**Comment by andreyorst** [comment]
Hm, that's interesting idea. I'll implement this
