### ISSUE TITLE
Command to add project non-interactively

### ISSUE THREAD

**Issue by krobelus** [andreyorst/fzf.kak#52]
I'd like to have a convenient way to automatically add projects.
For that I think we should expose a command like `fzf-save-path-as-project` but without the prompt.

So I can use, say `:fzf-project-add /path/to/project project-name` to add the current project on startup, or when changing directories.

I propose that when only one parameter is given, the name should default to the basename.
Right now I'm using this:

```sh
eval %sh{
    project_root="$(git rev-parse --show-toplevel)"
    if [ -n "$project_root" ]; then
    	line="$(basename "$project_root"):  $project_root"
    	grep -qFx "$line" "$kak_opt_fzf_projects_file" || {
        	echo "$line" >> "$kak_opt_fzf_projects_file"
    	}
    fi
}
```

with a new command this can be simplified

```sh
eval %sh{
    project_root="$(git rev-parse --show-toplevel)"
    if [ -n "$project_root" ]; then
        printf %s\\n "fzf-project-add $project_root"
    fi
}
```

**Comment by andreyorst** [comment]
How would this command behave in case project with such name already exists? Currently I'm providing a `y/N` chooser in this case, but this is interactive aspect.

**Comment by andreyorst** [comment]
@krobelus I've added a function `fzf-add-project` that accepts the path as first argument and generates name if not specified from path basename, but it still will prompt you, unless you add `-force` flag.

**Comment by krobelus** [comment]
On Sun, Apr 07, 2019 at 09:11:35AM -0700, Andrey Orst wrote:
> @krobelus I've added a function `fzf-add-project` that accepts the path as first argument and generates name if not specified from path basename, but it still will prompt you, unless you add `-force` flag.

Great, `-force` works nicely for me, thanks!

In future it might be useful to allow multiple projects with identical
names (identified by path or the entire line) but that's not really
important. I think projectile does something like that.
