### ISSUE TITLE
[Feature Request] yank-ring

### ISSUE THREAD

**Issue by losnappas** [andreyorst/fzf.kak#53]
hi

tried making a module to work with https://github.com/alexherbo2/yank-ring.kak .

Here is what I got done

```
try %{ declare-user-mode fzf }
map global fzf -docstring "open yank-ring" 'y' '<esc>: fzf-yank-ring<ret>'

define-command -hidden fzf-yank-ring %{ evaluate-commands %sh{
    yanks=$(mktemp ${TMPDIR:-/tmp}/kak-fzf-yanks.XXXXXX)
    eval "set -- $kak_opt_yank_ring_history"
    while [ $# -gt 0 ]; do
        printf "%s\0" "$1" >> $yanks
        shift
    done

    message="Set buffer to edit in current client.
<ret>: switch to selected buffer.
<c-w>: open buffer in new window"
    [ ! -z "${kak_client_env_TMUX}" ] && tmux_keybindings="
<c-s>: open buffer in horizontal split
<c-v>: open buffer in vertical split"
    printf "%s\n" "info -title 'fzf yanks' '$message$tmux_keybindings'"
    [ ! -z "${kak_client_env_TMUX}" ] && additional_flags="--expect ctrl-v --expect ctrl-s"

    printf "%s\n" "fzf -fzf-args %{--read0} -kak-cmd %{set-register dquote} -items-cmd %{(cat $yanks ; rm $yanks)}"
}}
```

It's incomplete. It bugs out on newlines and I want my yanks to keep their lines, obviously. It looks alright in fzf; everything is on 1 line all well, supposedly the newlines are still in there too, but selecting a yank only takes the part after the last newline. I think it's the `set-register dquote` part.

Thoughts? How do I wrap the string that gets out of fzf?

**Comment by losnappas** [comment]
```
try %{ declare-user-mode fzf }
map global fzf -docstring "open yank-ring" 'y' '<esc>: fzf-yank-ring<ret>'

define-command fzf-yank-ring- -params .. %{
    set-register dquote %sh{ echo $kak_reg_X }
}


define-command -hidden fzf-yank-ring %{ evaluate-commands %sh{
    yanks=$(mktemp ${TMPDIR:-/tmp}/kak-fzf-yanks.XXXXXX)
    eval "set -- $kak_opt_yank_ring_history"
    while [ $# -gt 0 ]; do
        printf "%s\0" "$1" >> $yanks
        shift
    done

    message="Swap between yanks."

    printf "%s" "fzf -fzf-args %{--read0} -kak-cmd %{set-register X} -items-cmd %{(cat $yanks | awk 1 ORS='NL_PH'; rm $yanks)} -filter %{ sed -e 's/NL_PH/\\\n/g' -e \"s/'//g\" } -post-action %{ fzf-yank-ring- }"
}}
```

it likes to insert quotes on its own but other than that, it kinda works.

**Comment by andreyorst** [comment]
Maybe just:
```kak
try %{ declare-user-mode fzf }
map global fzf -docstring "open yank-ring" 'y' '<esc>: fzf-yank-ring<ret>'

define-command -hidden fzf-yank-ring %{ evaluate-commands %sh{
    yanks=$(mktemp ${TMPDIR:-/tmp}/kak-fzf-yanks.XXXXXX)
    eval "set -- $kak_opt_yank_ring_history"
    while [ $# -gt 0 ]; do
        item=$(printf "%s" "$1" | awk 1 ORS='␤')
        printf "%s\n" "$item" >> $yanks
        shift
    done

    message="Swap between yanks."

    printf "%s" "fzf -kak-cmd %{set-register dquote} -items-cmd %{cat $yanks} -filter %{sed \"s/␤/\\\n/g;s/^'|'$//\"}"
}}
```

**Comment by andreyorst** [comment]
I've added this to the plugin. Now we need to find a proper way to define the shortcut only if yank-ring.kak is installed. @alexherbo2 is there any way to do so?

**Comment by alexherbo2** [comment]
Not without a hack.

``` kak
try %{
  # A guard for the Yank Ring plug-in.
  # Raise an error if the history option has not been declared.
  echo -to-file /dev/null %opt(yank_ring_history)
  map …
}
```

**Comment by losnappas** [comment]
Yeah, uh... that filter sed isn't letting anything through. Nothing gets pasted.

Take out the `\\\n`, and it goes back to outputting no linebreaks and quotes included, like so: `'aabb'` (newline between a and b).

**Comment by alexherbo2** [comment]
How usable is the module with long pastes and multiple selections?

**Comment by losnappas** [comment]
Should be ok. It's pretty easy to find stuff with fzf, after all. And it's like a history preview at the same time, which is nice.

**Comment by losnappas** [comment]
```
define-command -hidden fzf-yank-ring- -params .. %{
    set-register dquote %sh{ echo $kak_reg_X | tail -c +2 | head -c -2 }
}

define-command -hidden fzf-yank-ring %{ evaluate-commands %sh{
    yanks=$(mktemp ${TMPDIR:-/tmp}/kak-fzf-yanks.XXXXXX)
    eval "set -- $kak_opt_yank_ring_history"
    while [ $# -gt 0 ]; do
        printf "%s\0" "$1" >> $yanks
        shift
    done

    message="Swap between yanks."

    printf "%s" "fzf -fzf-args %{--read0} -kak-cmd %{set-register X} -items-cmd %{(cat $yanks | awk 1 ORS='␤'; rm $yanks)} -filter %{ sed -e 's/␤/\\\n/g' -e \"s/'//g\" } -post-action %{ fzf-yank-ring- }"
}}
```

slightly modded the earlier version and this works for me, though it isn't pretty.

**Comment by alexherbo2** [comment]
@losnappas I’m not using `fzf.kak` but I’m curious how it looks with multi-line.  Can you show me a picture?

**Comment by andreyorst** [comment]
> Not without a hack.
> 
> ```
> try %{
>   # A guard for the Yank Ring plug-in.
>   # Raise an error if the history option has not been declared.
>   echo -to-file /dev/null %opt(yank_ring_history)
>   map …
> }
> ```

yeah, I thought about it, but this means that yank ring plugin must be defined before fzf plugin. I guess a hook will do.

**Comment by andreyorst** [comment]
> Yeah, uh... that filter sed isn't letting anything through. Nothing gets pasted.
> 
> Take out the `\\\n`, and it goes back to outputting no linebreaks and quotes included, like so: `'aabb'` (newline supposed to be between a and b).

weird. What are your environments? Im usinng dash as kakoune posix shell and everything is working for me

**Comment by andreyorst** [comment]
> @losnappas I’m not using `fzf.kak` but I’m curious how it looks with multi-line. Can you show me a picture?

it convertrs newlines into unicode newline symbol, so paragraph will become a long line in fzf

**Comment by andreyorst** [comment]
This should work now. I've simplified the code, and there should be no breakages, but I'm not sure how this will work on OSX with non-gnu `awk` and `sed`.

**Comment by losnappas** [comment]
Works great. Milestone for version 1337: could show the yank in fzf preview, like the 'files' search does.

Closin'.

**Comment by andreyorst** [comment]
> Milestone for version 1337: could show the yank in fzf preview, like the 'files' search does.

Added preview :)

actually I can smell another problem here. User may want to copy `␤` and will receive newline instead.

**Comment by losnappas** [comment]
>actually I can smell another problem here. User may want to copy ␤ and will receive newline instead.

How many times in a millennium does that happen? 

Preview looks real nice.

**Comment by andreyorst** [comment]
> How many times in a millennium does that happen?

Indeed, I think if someone will report this, I'll think what to do here.
