### ISSUE TITLE
[Feature Request] Support stable kakoune

### ISSUE THREAD

**Issue by krobelus** [andreyorst/fzf.kak#60]
At some point it will be useful to support the released version of kakoune, I think most other plugins do that by default.

Right now, b924eaaade5cb296885ec652df3ac4c6938f0733 seems to work with stable. Maybe we can have a branch for that, it should be easy to check out the branch when installing with plug.

**Comment by andreyorst** [comment]
You can use tags. [Latest fzf.kak release](https://github.com/andreyorst/fzf.kak/releases/tag/v1.0.1) works with stable Kakoune. plug.kak supports tags: 

    plug "andreyorst/fzf.kak" tag "v1.0.1"

plug.kak also supports checking out to commit by hash directly:

    plug "andreyorst/fzf.kak" tag "b924eaa"

 in case you want something that is more new than the latest release.

**Comment by krobelus** [comment]
Thanks, that's perfect!
