### ISSUE TITLE
Error on first invokation of fzf-mode

### ISSUE THREAD

**Issue by SolitudeSF** [andreyorst/fzf.kak#65]
Not sure if thats issue of the plugin or my configuration, since module system made everything a bit more complicated.

This is all the line relevant to fzf in my kakrc:
```
hook global ModuleLoaded fzf %{
    set global fzf_implementation sk
    set global fzf_file_command fd
    set global fzf_highlight_cmd bat
    set global fzf_sk_grep_command 'rg -LHn'
}
```

On the first invokation of `:fzf-mode` kakoune writes this error to `*debug*`:
```
error running hook ModuleLoaded(fzf)/: 4:78: 'set' option not found: 'fzf_highlight_cmd'. Use declare-option first
```
... but opens the usermode menu anyway.

Consecutive invocations of `fzf-mode` work normally.

**Comment by andreyorst** [comment]
the last update changed all `_cmd` options to `_command` for consistency

**Comment by SolitudeSF** [comment]
ive read the commit messages, but didnt register this. thanks!
