### ISSUE TITLE
New Buffer in new Window switches both windows.

### ISSUE THREAD

**Issue by Icantjuddle** [andreyorst/fzf.kak#66]
## Problem description
Opening a new file from the vcs chooser mode makes both the original window from which the fzf chooser was entered from, and the new window it creates show the new buffer. Instead the original window should continue to display whatever buffer it did before opening the chooser.

## Steps to reproduce

1.Have a buffer open in a window.
2.Use fzf vcs file chooser to select a not yet open file.
3.Both windows will now show the new buffer.

## What should happen
I would expect only the new window to show the new buffer.

## What happens instead
Both the original and the new window display the new buffer

## Environment information
Kakoune version: 
OS version: Ubuntu 16.04
`sh` executable version: `zsh 5.7.1`
fzf version: 0.18.0
`git` version: 2.23

**Comment by andreyorst** [comment]
I can reproduce it too. I'll look into it

On a side note, linking `zsh` to `sh` is a dangerous move. `zsh` is not strictly POSIX complaint shell, therefore some scripts that use `sh` will break. Especially in Kakoune, where POSIX scripting is the way to go. My suggestion would be to use `dash` for Kakoune (and `sh` if there's no scripts filled with bashisms on your system) via `$KAKOUNE_POSIX_SHELL` environment variable.

**Comment by andreyorst** [comment]
Actually, this can be reproduced with any fzf command. That's weird

**Comment by Icantjuddle** [comment]
yes it is, my `zsh` is not linked to `sh`, I misinterpreted that line to be just "What shell are you running this from" though on reflection that makes little sense. `sh` should be `dash` on mine.

**Comment by andreyorst** [comment]
Should be fixed now. If not, please report back, I'll continue investigation

**Comment by Icantjuddle** [comment]
Looks like it worked, thanks so much!
