### ISSUE TITLE
[Feature Request] Grep with FZF

### ISSUE THREAD

**Issue by gbrlsnchs** [andreyorst/fzf.kak#71]
First of all, thanks for this plugin, it's great and works very well.

However, I noticed there is no way to grep files using FZF, only `skim`. Are there any technical reasons for that? It would be awesome if grepping was available for FZF, as that's the fuzzy finder I'm used to.

Thanks!

**Comment by andreyorst** [comment]
> Are there any technical reasons for that?

yeah, it is impossible with fzf

**Comment by gbrlsnchs** [comment]
Would you mind describing what prevents it to work with FZF? I'm new to Kakoune and would like to help, but of course I don't want to be banging my head against the wall with an unsolvable issue...

**Comment by andreyorst** [comment]
https://github.com/junegunn/fzf/issues/751

**Comment by andreyorst** [comment]
also, you can use `skim` only for grepping, and `fzf` for everything else. This is default behavior.

**Comment by gbrlsnchs** [comment]
I see... I still think the simple filtering behavior would be enough, though... something like `rg --line-number . | fzf` works okay. I really don't want to have two fuzzy finders installed... well, I guess I will try something that satisfies my needs myself. Thanks nonetheless!
