### ISSUE TITLE
grep with skim overrides dquote register

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/fzf.kak#72]
I've noticed that grep with skim, [overrides](https://github.com/andreyorst/fzf.kak/blob/9a10a6b64ae34261591c9a6381731c3659607fdc/rc/modules/sk-grep.kak#L66) my `"` register. Is it possible to preserve it?

I've tried `-save-regs dquote` like below, but it didn't help.
```
    evaluate-commands -save-regs dquote -buffer *grep* %{
        set-register dquote %arg{1}
        execute-keys gjPo
    }
```

**Comment by andreyorst** [comment]
should be fixed
