### ISSUE TITLE
FZF tmux window is shown in wrong tmux session

### ISSUE THREAD

**Issue by krobelus** [andreyorst/fzf.kak#73]
When running a single kakoune session with two connected clients that are in different tmux sessions, the fzf split can open in the wrong client.

## Steps to reproduce
```sh
#!/bin/sh
tmux='tmux -L tempsocket'
$tmux new-session -s a -d
$tmux new-session -s b -d
$tmux send-keys -t a 'kak -s kak-session' Enter
$tmux send-keys -t b 'kak -c kak-session' Enter
$tmux send-keys -t b ':fzf-mode' Enter 'b'
$tmux attach -t b
# $tmux kill-server
```

## What should happen
The fzf split should be done in the client in tmux session `b`. 

## What happens instead
The fzf split shows up in the first client in tmux session `a`.

Changing this possibly requires some support from kakoune because currently both clients execute commands as if they were in the same tmux session. It's not a huge issue though.

## Environment information
Kakoune version: 2019.07.01-1
OS: Arch linux
`sh` version: GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
`sk` version 0.6.9

**Comment by andreyorst** [comment]
Boy oh boy... This may be related to `tmux`, because I invoke `tmux` commands manually and I do not specify session or something. Though, I do not know if it is possible

**Comment by krobelus** [comment]
Looks like there is an easy fix :)
