### ISSUE TITLE
[Feature Request] Show relative paths in fzf-vcs

### ISSUE THREAD

**Issue by jcpetruzza** [andreyorst/fzf.kak#75]
I usually use `fzf-vcs` to open files from a git repository. In that case I get the full paths to the files. I find this not ideal: a common prefix carries zero information but `fzf` will try to match against that as well, making some suggestions less relevant.

There are two ways in which this could be improved, I think::

  1. Show paths relative to the root of the repository instead.
  2. Show paths relative to the cwd (and exclude those files that lie outside)

I have a slight preference for 2, since for large repositories that allows one to focus only on a section of it (which again, reduces the number of suggestions, etc), but otherwise both would be fine for me.

**Comment by andreyorst** [comment]
I will look into this, but I'm currently in the progress of transition my repositories to gitlab, so I'm not sure if you will be able to ping you here once this is done. Do you have gitlab account?

**Comment by jcpetruzza** [comment]
Yes, same handle should work on gitlab as well. Thanks!

**Comment by andreyorst** [comment]
oh, apparently I forgot to close this, as fixed! This should be fixed for Git and GNU Bazaar in 8a8414fb573c40dd6f88ea78ea97fba364da6370
