### ISSUE TITLE
[Feature Request] Add a way to enable fzf preview

### ISSUE THREAD

**Issue by Delapouite** [andreyorst/fzf.kak#8]
Hi Andrey. Thanks for making this great plugin.

I've been using the following shell script for a while:
```sh
#!/bin/sh

# sleep needed to get real dimensions
sleep 0.1
COLUMNS=$(tput cols)
LINES=$(tput lines)
# multiply by 2 to roughly approximate the size of a cell
LINES=$(expr $LINES \* 2)

[ $COLUMNS -gt $LINES ] && pos=right:50% || pos=top:60%

export FZF_DEFAULT_COMMAND='rg --files'
fzf \
  --select-1 \
  --multi \
  --preview="~/bin/preview.rb {} | head -n 100" \
  --preview-window=$pos \
  --bind 'ctrl-t:toggle-preview' \
  --bind 'ctrl-x:execute($EDITOR {})' \
| xargs $EDITOR
```

Here's a screenshot to explain what it does:
![image](https://user-images.githubusercontent.com/39315/46244811-f1b60d80-c3e4-11e8-935d-899bd978c039.png)

They are 2 terminals: one with kakoune on the left and one with fzf on the right.

What I enjoy about this setup is that I can navigate the fzf list on the bottom right and having the preview of the file on the top right.

Meanwhile, if the terminals are splitted the other way around, with kakoune in the top terminal and fzf in the bottom one, the preview goes on the right side of the fzf terminal:
![image](https://user-images.githubusercontent.com/39315/46244846-815bbc00-c3e5-11e8-8857-8fc51eb2fde2.png)

Would it be possible to integrate the fzf preview in your plugin as well? Thanks!

**Comment by andreyorst** [comment]
It is certainly possible. I'll add this as a switchable option

**Comment by vbauerster** [comment]
@andreyorst You may benefit of what I already made here https://github.com/vbauerster/fzf.kak/blob/file-preview/rc/fzf.kak#L101
If [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php) command is available, it will be used. Also I've limited preview for 200 lines. It works for me, but If you think it deserves a PR, I can submit.
[![20180929-190420.png](https://i.postimg.cc/VLW59mhq/20180929-190420.png)](https://postimg.cc/nCMHpbpr)

**Comment by andreyorst** [comment]
@vbauerster this is great! Yeah I'll very much appreciate a PR, however I would like to add some features to make it more configurable

**Comment by andreyorst** [comment]
@Delapouite @vbauerster is it worth to add a variable so user could choose a default preview programm, or `preview` itself is enough? I think that variable is needed, but I don't use previews with fzf, and I don't know if there are other programs that can be used with it.

**Comment by vbauerster** [comment]
I think, it's better just to list supported preview highlighters, as it is done at fzf main [page](https://github.com/junegunn/fzf#preview-window). What is really necessary is to add ability to adjust default size and position. I'm ok with just bottom position, but default height 15 is too small for me.

**Comment by andreyorst** [comment]
> What is really necessary is to add ability to adjust default size and position.

Yeah, I've thought about this too, when saw your PR. It will be possible, for sure.

> I think, it's better just to list supported preview highlighters, as it is done at fzf main page. 

Ok. I'll do it in the same way script works with file command.

**Comment by andreyorst** [comment]
@Delapouite  @vbauerster  I've pushed changes to https://github.com/andreyorst/fzf.kak/tree/preview. If it possible I'd like to ask you to test it with your environments.

**Comment by andreyorst** [comment]
Before you say it, I see that dimension calculation isn't working properly. Already working on it.

**Comment by andreyorst** [comment]
with latest changes at `preview` branch preview position should be calculated properly.

**Comment by andreyorst** [comment]
so?

**Comment by andreyorst** [comment]
I've merged this to master. If you will experience any troubles please open separate issue
