### ISSUE TITLE
[Question] How to use with skim interactive mode

### ISSUE THREAD

**Issue by jtrees** [andreyorst/fzf.kak#80]
I'm trying to figure out how to get this plugin to work with skim interactive mode. When I'm grepping, I essentially want this to run:

```sh
sk --interactive --cmd 'rg {}'
```

Any ideas on how to achieve this?

**Comment by andreyorst** [comment]
There's a module for skim that does interactive grep: https://github.com/andreyorst/fzf.kak/blob/master/rc/modules/sk-grep.kak

**Comment by jtrees** [comment]
Wow, that was fast! And thanks! Can't believe I missed it.
