### ISSUE TITLE
fzf_preview_tmux_height not working

### ISSUE THREAD

**Issue by pianocomposer321** [andreyorst/fzf.kak#83]
I'm new to kakoune, and I tried installing your plugin like so:

```
plug "andreyorst/fzf.kak" config %{
    set-option global fzf_preview_tmux_height '25%'
}
```

But the preview window still takes up 70% of the height of the window, and `:echo %opt{fzf_preview_tmux_height}` outputs 70%.

Any ideas?

**Comment by pianocomposer321** [comment]
Never mind, I figured it out.

For posterity, I needed to call the set-option outside of the config section, and I needed to require-modeule fzf first.

**Comment by andreyorst** [comment]
maybe I should update the README to make it a bit more clear?

**Comment by pianocomposer321** [comment]
IDK, I just looked at the readme again, and it is there (the first paragraph in the Configuration section), I just missed it. It may be a good idea to put it somewhere where new users would see it better, but then again, where would you put it? I just missed it because I was trying to figure out how to make the files command not take up 70% of my screen real estate. So I just did ctrl-f and searched for height. I didn't see anything about needing to require the fzf module, not because it wasn't there, but because I didn't look for it. I didn't look for it because I didn't know to look for it. But now that I've had this experience I know that any time I get an error about an option not being declared, It's probably because I need to use a defer block. So you could see it both ways. It's not your fault, because it was in the readme. It's not my fault, because I didn't know to look for it. But now I do, so I won't likely run into the same problem again.

**Comment by andreyorst** [comment]
I see, thanks. I have plans of refactoring this plugin, so I will definitively overhaul the readme in the future. There are some inconsistencies in how I've used the module system.
