### ISSUE TITLE
Main selection ignored in fzf search

### ISSUE THREAD

**Issue by jordan-yee** [andreyorst/fzf.kak#87]
## fzf.kak installation & config in kakrc
It looks like fzf was refactored into a bunch of modules, and not all the options I had previously set are mentioned in the README. Below was a best-guess attempt at updating my fzf.kak config to the latest version in a way that I think `defer`s the right modules.

```
plug "andreyorst/fzf.kak" config %{
    map global normal <c-p> ': fzf-mode<ret>'
} defer "fzf-file" %{
    set-option global fzf_file_command 'fdfind --hidden --type f --exclude .git'
    set-option global fzf_highlight_command 'bat'
} defer "fzf-cd" %{
    set-option global fzf_cd_command 'fdfind --follow --hidden --type d --exclude .git'
} defer "fzf-grep" %{
    set-option global fzf_grep_command 'rg'
}
```

## Problem description
The fzf prompt is always empty when doing a search, as though the fzf_use_main_selection were false. This is the case when testing with kitty, tmux, or st in an x11 window manager (dwm).

It should also be noted that `:echo %opt{fzf_use_main_selection}` prints `true`.

## Steps to reproduce

1. Open `kak`
2. Select a word (selection > 1 char)
3. Open an fzf search: ctrl+p, f
4. The fzf file search opens successfully, but with a clear search prompt

## What should happen

Following the above steps, the main selection should populate as the search term in step 4.

## What happens instead

See step 4 in "Steps to reproduce section".

## Environment information
Kakoune version: Kakoune v2020.09.01-404-g212242cc
OS version: Ubuntu 20.04
`sh` executable version: zsh 5.8 (x86_64-ubuntu-linux-gnu)
fzf version:  0.20.0

**Comment by andreyorst** [comment]
Just to make sure, you use plug.kak from development branch? I've changed how the `defer` keyword works, and haven't updated the main branch there yet, but added new config to readme here...

Weird that it doesn't work for you as it surely works on my end.

**Comment by jordan-yee** [comment]
I was using the master branch, not the development branch. It looks like you just merged it in, but updating didn't seem to change anything (nor did checking out the develop branch). If it's working as expected for you, then I guess I'll have to dig deeper on my system.

**Comment by jordan-yee** [comment]
Some more test results:
- I started over with a clean config directory and setup a kakrc with only plug.kak and fzf.kak. Same problem.
- Running the following command in the kakoune prompt works (fzf is opened in a new terminal with the selection as the query text):
  `:terminal fzf -q %val{selection}`

**Comment by andreyorst** [comment]
Aha, I've reproduced it.

**Comment by andreyorst** [comment]
Basically this commit 4e6c9a857511fccdbbc835a1c9acb205b6486a4c added a check that there's only one line, but when there's no newlines int the selection at all, this test results in `false`. I'll fix it soon
