### ISSUE TITLE
fzf opens and closes immediately

### ISSUE THREAD

**Issue by benjaminweb** [andreyorst/fzf.kak#89]
## Problem description

fzf opens and closes immediately

consulting the thread of https://github.com/andreyorst/fzf.kak/issues/15 did not help debugging the undesired behaviour

@andreyorst  _**How can I debug the failing call of fzf from kak?**_

## Steps to reproduce

1. `kak somefile.txt`
2. `ctrl+p`
3. `f`

## What should happen
fzf window should open and not close immediately

## What happens instead
fzf window opens and closes immediately without showing error message

## Environment information
Kakoune version: v2020.09.01
iTerm2 version: 3.3.12
OS version: macOS 10.13.6
`sh` executable version: fish, version 3.1.2 (issue persists with bash & zsh)
fzf version:  0.24.3 (brew)

`~/.config/kak/kakrc`
```
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload config %{}
plug "andreyorst/fzf.kak"
map global normal <c-p> ': fzf-mode<ret>'
```

**Comment by andreyorst** [comment]
I've pushed a `debug` branch, which writes `stderr` into a `/tmp/fzf.kak.errors` file when launching the fzf command. See if something lends there

**Comment by benjaminweb** [comment]
`/tmp/fzf.kak.errors` is not being created.

fzfcmd gets created:

`/var/folders/mx/v5148n45119165d54fyd736r0000gp/T/fzf.kak.RFbR4g/fzfcmd`
```
#!/usr/local/bin/sh
SHELL=/usr/local/bin/sh
export FZF_DEFAULT_OPTS=""
cd ~ && sleep 0.1; [ $(tput cols) -gt $(expr $(tput lines) \* 2) ] && pos=right:50% || pos=top:60%; find -L . -type f 2>/dev/null | fzf  -m --expect ctrl-w  --preview '(highlight --failsafe -O ansi {} || cat {}) 2>/dev/null | head -n 100' --preview-window=${pos}  2>&1 > /var/folders/mx/v5148n45119165d54fyd736r0000gp/T//fzf.kak.RFbR4g/result | tee "/var/folders/mx/v5148n45119165d54fyd736r0000gp/T//fzf.kak.errors"
rm /var/folders/mx/v5148n45119165d54fyd736r0000gp/T//fzf.kak.RFbR4g/fzfcmd
```

Once I execute
```
bash /var/folders/mx/v5148n45119165d54fyd736r0000gp/T/fzf.kak.RFbR4g/fzfcmd
```

`/var/folders/mx/v5148n45119165d54fyd736r0000gp/T/fzf.kak.errors` is created, fzfcmd disappears.

`fzf.kak.errors` includes

```
fish: Command substitutions not allowed (highlight --failsafe -O ansi 'file.txt'
```

`command -v sh` (in ) returns `/usr/local/bin/sh` that links to `/usr/local/bin/fish`

I changed the link to point to `/bin/bash`.

Reload fish, Kakoune.

Works.

**Comment by andreyorst** [comment]
yeah, linking `sh` to a non POSIX shell is a recipe to break a lot of scripts that use `#!/bin/env sh` or `#!/usr/bin/sh` shebangs, because `sh` is expected to be POSIX complaint, which `fish` is not.

Were linking `sh` to `fish` done by MacOS? IIRC they've replaced Bash with Zsh some time ago, because of Bash's GPL-v3 license.

**Comment by benjaminweb** [comment]
> yeah, linking `sh` to a non POSIX shell is a recipe to break a lot of scripts that use `#!/bin/env sh` or `#!/usr/bin/sh` shebangs, because `sh` is expected to be POSIX complaint, which `fish` is not.

> Were linking `sh` to `fish` done by MacOS? IIRC they've replaced Bash with Zsh some time ago, because of Bash's GPL-v3 license.


Can't say. I've installed heirloom-sh and fish, sh linked originally to heirloom-sh. So rather a non-default setup.

Would a hint "`command -v sh` should return a POSIX compliant shell like x,y (not z …), otherwise fzf.kak will not work" on the README make sense?

**Comment by andreyorst** [comment]
> Would a hint "`command -v sh` should return a POSIX compliant shell like x,y (not z …), otherwise fzf.kak will not work" on the README make sense?

It does make sense, but it does so for any Kakoune script. I think that I may use the `$KAKOUNE_POSIX_SHELL` env variable to make it a bit more portable, e.g. allowing linking `sh` to anything user wants, but this variable is not well documented or advertised by Kakoune AFAIK.
