### ISSUE TITLE
doesn‘t work

### ISSUE THREAD

**Issue by lougxing** [andreyorst/fzf.kak#94]
I press <kbd>ctrl-p</kbd>, it display the correct tip (f s b...), then I press f (open file),  it display the tip of  (<kbd>ret</kbd>: <kbd>ctrl-w</kbd>:), but it doesn't appear the files list. 

My kak 's version is master (commit b3a1017a264cfea7e9ae1a374208e9b02efbda5a ).

follow is my all config.

```
add-highlighter global/ number-lines
colorscheme solarized-dark

hook global WinSetOption filetype=(c|cpp|cc) %{
    clang-enable-autocomplete
    clang-enable-diagnostics
}

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "andreyorst/fzf.kak"

plug "danr/kakoune-easymotion"

plug "andreyorst/powerline.kak" defer powerline %{
    set-option global powerline_ignore_warnings true
    set-option global powerline_format 'git bufname langmap smarttab mode_info filetype client session position'
    set-option global powerline_separator '║'
    set-option global powerline_separator_thin ''
} defer powerline_bufname %{
    set-option global powerline_shorten_bufname 'short'
} defer powerline_solarized_dark %{
    powerline-theme solarized-dark
} config %{
    powerline-start
}

map global normal <c-p> ': fzf-mode<ret>'
```

**Comment by lougxing** [comment]
1. I use windows  WSL2(ubuntu20.04). 
2. 1. in tmux,  it work. 
3. not in tmux, The error message is  "terminal no such command".

**Comment by andreyorst** [comment]
I'm sure that Kakoune under WSL2 does not register a `terminal` command alias, which is registered [here](https://github.com/mawww/kakoune/tree/master/rc/windowing) for various windowing systems (For example, [for X11](https://github.com/mawww/kakoune/blob/master/rc/windowing/x11.kak#L67)). WSL doesn't have any windowing really, so it's essentially the same as running Kakoune in plain Linux TTY, where you will have the exact same problem.

So you have two options, either to use Tmux (which I think is the way to go), or to add Windows windowing support to Kakoune, which may be very tricky to do.

**Comment by lougxing** [comment]
I got it, thanks.
