### ISSUE TITLE
[Feature Request] Order buffers according to which has been last used

### ISSUE THREAD

**Issue by catdevnull** [andreyorst/fzf.kak#96]

**Comment by andreyorst** [comment]
`fzf` is meant for fuzzy selection. Using it as an ordered menu is kind of impractical tbh.

I guess to achieve this, a custom `fzf` command can be made, that does the sorting and feeds `fzf` the correct options to force a certain order of the elements.

**Comment by catdevnull** [comment]
> Using it as an ordered menu is kind of impractical tbh.

I find it's useful for finding files with the files finder, but selecting buffers also works pretty well. I'm trying to figure out how to make Kakoune tell me when buffers were last shown to implement it locally.

**Comment by andreyorst** [comment]
maybe not exactly what you want, but I have a `recentf` function in my configuration, that keeps an updated list, which is sorted. It has a `fzf` command as well: https://github.com/andreyorst/dotfiles/blob/master/.config/kak/recentf.kak

**Comment by andreyorst** [comment]
I'm going to close this, as the solution here is to write a custom module, as suggested in my previous comment.
