### ISSUE TITLE
Setting flags for fzf_grep_command is impossible

### ISSUE THREAD

**Issue by TeddyDD** [andreyorst/fzf.kak#97]
## Problem description

Setting `fzf_grep_command` to `rg -niL` results in empty grep list

## Steps to reproduce

1. `set-option global fzf_grep_command 'rg -niL'`
2. `fzf-grep`
3. fzf shows up empty

## What should happen

fzf split panel with grep results shows up

## What happens instead

fzf split panel shows up, but there are no results

Setting `fzf_grep_command` to `rg` results in correct behavour - fzf window is populated with search results.

## Environment information
Kakoune version: `Kakoune v2021.11.08`
OS version: `Void 5.15.12_1 x86_64`
`sh` executable version: `dash 0.5.11.5`
fzf version:  `0.28`

**Comment by andreyorst** [comment]
`rg -niL ''` will do

**Comment by andreyorst** [comment]
Basically, this mode is a little cheat, as it does a search for an empty pattern, which results in displaying all lines from all files, and allows you to quickly match them with fzf. Because interactive isn't a feature of fzf, this way we can achieve a rather robust pseudo interactive grep. So case sensitiveness here is not important at all.

**Comment by TeddyDD** [comment]
Good to know. It seems that sk version works by relaunching grep on every key pres right?

**Comment by andreyorst** [comment]
I'm not sure I remember it right at this point, but seems so. Sk supports interactive execution, but I never found it really useful, given that fzf is a list narrowing framework, not a selection menu. So narrowing contents of all files, while hacky, still legit approach.

Perhaps the empty pattern thing should be documented a bit better in the `fzf_grep_commamd` option

**Comment by TeddyDD** [comment]
Okay, thanks!
